### PR TITLE
APP-99883 Update Uasurfer Repo to Handle Motorola Razr User Agent

### PR DESCRIPTION
**Pull request by jmartin-code**
Dev Testing:
- [x] Unit test seems to be enough here. More testing to be done with app engine library update. 

Updating repo to include handle for Mororola Razr phone device.
 

Screenshot 2024-04-08 at 9 05 46 AM

- - -
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/uasurfer/12)

### CODE REVIEW

**Review by travis-barnett — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/uasurfer/12)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @jmartin-code and @larajohn)

___
*[`.gitignore` line 57 at r1](https://reviewable.io/reviews/pendo-io/uasurfer/12#-NuyGWSX6IXys4daUpH5:-NuyGWSY0Fu78-ad2VM0:b-n1zp9b) ([raw file](https://github.com/pendo-io/uasurfer/blob/01d16c8f3cab4b64f16164dcf3e3c78f613d1970/.gitignore#L57)):*
> ```ignore
> ######################
> .vagrant
> .idea
> ```

nit: I'm not sure this is really necessary

**Comment by jmartin-code** [comment]
*[`.gitignore` line 57 at r1](https://reviewable.io/reviews/pendo-io/uasurfer/12#-NuyGWSX6IXys4daUpH5:-NuyH1Yf19FqxIibTZX2:bkw5muw) ([raw file](https://github.com/pendo-io/uasurfer/blob/01d16c8f3cab4b64f16164dcf3e3c78f613d1970/.gitignore#L57)):*
<details><summary><i>Previously, travis-barnett wrote…</i></summary><blockquote>

nit: I'm not sure this is really necessary
</blockquote></details>

It probably something to do with my IDE settings. For me the golang IDE is adding a bunch of extra `.idea` files and I had to ignore `.idea`.

**Comment by jmartin-code** [comment]
*[`.gitignore` line 57 at r1](https://reviewable.io/reviews/pendo-io/uasurfer/12#-NuyGWSX6IXys4daUpH5:-Nuz9sMj4ZFwrrVh8zK7:b-ksyj6o) ([raw file](https://github.com/pendo-io/uasurfer/blob/01d16c8f3cab4b64f16164dcf3e3c78f613d1970/.gitignore#L57)):*
<details><summary><i>Previously, jmartin-code (Jonathan Martinez) wrote…</i></summary><blockquote>

It probably something to do with my IDE settings. For me the golang IDE is adding a bunch of extra `.idea` files and I had to ignore `.idea`.
</blockquote></details>

Ok. Figure it out. Added ignore under IDE `idea/.ignore` 👍🏼

**Review by larajohn — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/uasurfer/12#-:-Nv39qfcC9nzLbI4JJYp:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @travis-barnett)

**Review by travis-barnett — COMMENTED** [review]
[merge]

> *[Reviewable](https://reviewable.io/reviews/pendo-io/uasurfer/12#-:-Nv7HBYu6yWaF2fjMa4C:b3sq3yz)* status: all files reviewed, 1 unresolved discussion (waiting on @jmartin-code)

**Review by travis-barnett — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/uasurfer/12)* status: all files reviewed, 1 unresolved discussion (waiting on @jmartin-code)

**Review by travis-barnett — APPROVED** [review]
[merge]

> *[Reviewable](https://reviewable.io/reviews/pendo-io/uasurfer/12#-:-Nv7HM676vRjGkGWXIJ8:b3sq3yz)* status: all files reviewed, 1 unresolved discussion (waiting on @jmartin-code)

**Pull request merged**
